---
- name: install haproxy
  apt:
    name: haproxy
    state: present
  register : is_installed_haproxy

- name: copy haproxy template
  action: template src=../templates/etc/haproxy/haproxy.j2 dest=/etc/haproxy/haproxy.cfg
  when: is_installed_haproxy

- name: restart haproxy
  service:
    name=haproxy
    state=restarted
  when: is_installed_haproxy